let data=[
    {
        id:Symbol(),
        name:"张三",
        age:18,
        gender:"男",
        state:true,
        checked:true
    },
    {
        id:Symbol(),
        name:"李四",
        age:19,
        gender:"男",
        state:false,
        checked:false
    },
    {
        id:Symbol(),
        name:"小美",
        age:20,
        gender:"女",
        state:false,
        checked:true
    },
    {
        id:Symbol(),
        name:"小爱",
        age:21,
        gender:"女",
        state:true,
        checked:false
    },
    {
        id:Symbol(),
        name:"小赵",
        age:18,
        gender:"男",
        state:true,
        checked:true
    }
]